### ISSUE TITLE
Lack of device type option in document

### ISSUE THREAD

**Issue by freesky-edward** [huawei-clouds/terraform-provider-huaweicloud#9]
### Terraform Version
terraform 0.11.0

### Affected Resource(s)
-blockstorage v2

### Expected Behavior
I can find the way how to config a special disk in document.

### Actual Behavior
I cannot find the type name of device that supports by now in any of documents. e.g. https://github.com/huawei-clouds/terraform-provider-huaweicloud/blob/master/website/docs/r/blockstorage_volume_v2.html.markdown

propose to add the types of device supports description.

**Comment by niuzhenguo** [comment]
you mean volume_type here?

**Comment by freesky-edward** [comment]
not lack of volume_type but the value of volume_type can pick to config.

**Comment by niuzhenguo** [comment]
I managed to list the types on huawei cloud,
```
DSS_SAS
SSD
SATA
SAS
POD1
```

Should we maintain the available types list on our document? seems better to ask users to get it on huaweicloud API/help website.

**Comment by niuzhenguo** [comment]
I can provide a link if there is.

**Comment by freesky-edward** [comment]
linking other doc may be another way to fix this. I think it would be much great if user can finish config by only referring to one doc. what's your opinion?

**Comment by niuzhenguo** [comment]
yes it's true, but we need to keep sticking with the types updated, it's not static.

**Comment by freesky-edward** [comment]
yeah, it would be changed, but I don't think it will occur frequently. right?

**Comment by niuzhenguo** [comment]
yes, just checked the EVS API doc, only "SSD", "SATA", and "SAS" available now. Will add that with the volume_type.

**Comment by niuzhenguo** [comment]
@freesky-edward please have a look at the PR, thanks!
